name: org_flutter
description: Flutter widgets for displaying Emacs Org Mode (https://orgmode.org) content
version: 1.4.2
homepage: https://github.com/amake/org_flutter

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_highlight: ^0.7.0
  flutter_tex_js:
    git:
      url: https://github.com/luk3ya0/flutter_tex_js.git
      ref: master
      path: flutter_tex_js
  flutter_tikz_rust:
    git:
      url: https://github.com/luk3ya0/flutter_tikz_rust.git
      ref: main
  highlight: ^0.7.0
  org_parser:
    path: ../org_parser

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
